[target.aarch64-linux-android]
ar = "/Users/serhiizashchelkin/Library/Android/sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/serhiizashchelkin/Library/Android/sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android34-clang"
