// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.pman_lib;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the detils of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_pman_lib_rustbuffer_alloc(size, status).also {
                if(it.data == null) {
                   throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
               }
            }
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_pman_lib_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getInt(0))
        value.writeField("len", pointer.getInt(4))
        value.writeField("data", pointer.getPointer(8))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: RustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == 0.toByte()
    }

    fun isError(): Boolean {
        return code == 1.toByte()
    }

    fun isPanic(): Boolean {
        return code == 2.toByte()
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    checkCallStatus(errorHandler, status)
    return return_value
}

// Check RustCallStatus and throw an error if the call wasn't successful
private fun<E: Exception> checkCallStatus(errorHandler: CallStatusErrorHandler<E>, status: RustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// IntegerType that matches Rust's `usize` / C's `size_t`
public class USize(value: Long = 0) : IntegerType(Native.SIZE_T_SIZE, value, true) {
    // This is needed to fill in the gaps of IntegerType's implementation of Number for Kotlin.
    override fun toByte() = toInt().toByte()
    override fun toChar() = toInt().toChar()
    override fun toShort() = toInt().toShort()

    fun writeToBuffer(buf: ByteBuffer) {
        // Make sure we always write usize integers using native byte-order, since they may be
        // casted to pointer values
        buf.order(ByteOrder.nativeOrder())
        try {
            when (Native.SIZE_T_SIZE) {
                4 -> buf.putInt(toInt())
                8 -> buf.putLong(toLong())
                else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
            }
        } finally {
            buf.order(ByteOrder.BIG_ENDIAN)
        }
    }

    companion object {
        val size: Int
            get() = Native.SIZE_T_SIZE

        fun readFromBuffer(buf: ByteBuffer) : USize {
            // Make sure we always read usize integers using native byte-order, since they may be
            // casted from pointer values
            buf.order(ByteOrder.nativeOrder())
            try {
                return when (Native.SIZE_T_SIZE) {
                    4 -> USize(buf.getInt().toLong())
                    8 -> USize(buf.getLong())
                    else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
                }
            } finally {
                buf.order(ByteOrder.BIG_ENDIAN)
            }
        }
    }
}


// Map handles to objects
//
// This is used when the Rust code expects an opaque pointer to represent some foreign object.
// Normally we would pass a pointer to the object, but JNA doesn't support getting a pointer from an
// object reference , nor does it support leaking a reference to Rust.
//
// Instead, this class maps USize values to objects so that we can pass a pointer-sized type to
// Rust when it needs an opaque pointer.
//
// TODO: refactor callbacks to use this class
internal class UniFfiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<USize, T>()
    // Use AtomicInteger for our counter, since we may be on a 32-bit system.  4 billion possible
    // values seems like enough. If somehow we generate 4 billion handles, then this will wrap
    // around back to zero and we can assume the first handle generated will have been dropped by
    // then.
    private val counter = java.util.concurrent.atomic.AtomicInteger(0)

    val size: Int
        get() = map.size

    fun insert(obj: T): USize {
        val handle = USize(counter.getAndAdd(1).toLong())
        map.put(handle, obj)
        return handle
    }

    fun get(handle: USize): T? {
        return map.get(handle)
    }

    fun remove(handle: USize) {
        map.remove(handle)
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_pman_lib"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "pman_lib")
            .also { lib: _UniFFILib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
    }

    fun uniffi_pman_lib_fn_free_fileaction(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_method_fileaction_get_file_name(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_fileaction_get_data(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_free_databasegroup(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_method_databasegroup_get_name(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_databasegroup_get_id(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_method_databasegroup_get_entities_count(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_free_databaseentity(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_method_databaseentity_get_name(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_databaseentity_get_group_id(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_method_databaseentity_get_user_id(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_method_databaseentity_get_password(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_databaseentity_get_url(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_databaseentity_get_property_names(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_databaseentity_get_property_value(`ptr`: Pointer,`id`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_method_databaseentity_modify(`ptr`: Pointer,`newName`: RustBuffer.ByValue,`newGroupId`: RustBuffer.ByValue,`newUserId`: RustBuffer.ByValue,`newPassword`: RustBuffer.ByValue,`newUrl`: RustBuffer.ByValue,`newProperties`: RustBuffer.ByValue,`modifiedProperties`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_lib_init(_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_create(`databaseType`: RustBuffer.ByValue,`passwordHash`: RustBuffer.ByValue,`password2Hash`: RustBuffer.ByValue,`keyFileContents`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun uniffi_pman_lib_fn_func_prepare(`data`: RustBuffer.ByValue,`fileName`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun uniffi_pman_lib_fn_func_is_read_only(`databaseId`: Long,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_pman_lib_fn_func_pre_open(`databaseId`: Long,`passwordHash`: RustBuffer.ByValue,`password2Hash`: RustBuffer.ByValue,`keyFileContents`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_func_open(`databaseId`: Long,`data`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_save(`databaseId`: Long,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_func_close(`databaseId`: Long,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_set_argon2(`databaseId`: Long,`hashId`: Long,`iterations`: Long,`parallelism`: Long,`memory`: Long,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_get_groups(`databaseId`: Long,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_func_add_group(`databaseId`: Long,`name`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_func_delete_group(`databaseId`: Long,`id`: Int,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_get_users(`databaseId`: Long,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_func_add_user(`databaseId`: Long,`name`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_func_delete_user(`databaseId`: Long,`id`: Int,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_get_entities(`databaseId`: Long,`groupId`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_fn_func_add_entity(`databaseId`: Long,`name`: RustBuffer.ByValue,`groupId`: Int,`userId`: Int,`password`: RustBuffer.ByValue,`url`: RustBuffer.ByValue,`properties`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_pman_lib_fn_func_delete_entity(`databaseId`: Long,`id`: Int,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_pman_lib_fn_func_search(`databaseId`: Long,`searchString`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_pman_lib_rustbuffer_alloc(`size`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_pman_lib_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_pman_lib_rustbuffer_free(`buf`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun ffi_pman_lib_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_pman_lib_checksum_func_lib_init(
    ): Short
    fun uniffi_pman_lib_checksum_func_create(
    ): Short
    fun uniffi_pman_lib_checksum_func_prepare(
    ): Short
    fun uniffi_pman_lib_checksum_func_is_read_only(
    ): Short
    fun uniffi_pman_lib_checksum_func_pre_open(
    ): Short
    fun uniffi_pman_lib_checksum_func_open(
    ): Short
    fun uniffi_pman_lib_checksum_func_save(
    ): Short
    fun uniffi_pman_lib_checksum_func_close(
    ): Short
    fun uniffi_pman_lib_checksum_func_set_argon2(
    ): Short
    fun uniffi_pman_lib_checksum_func_get_groups(
    ): Short
    fun uniffi_pman_lib_checksum_func_add_group(
    ): Short
    fun uniffi_pman_lib_checksum_func_delete_group(
    ): Short
    fun uniffi_pman_lib_checksum_func_get_users(
    ): Short
    fun uniffi_pman_lib_checksum_func_add_user(
    ): Short
    fun uniffi_pman_lib_checksum_func_delete_user(
    ): Short
    fun uniffi_pman_lib_checksum_func_get_entities(
    ): Short
    fun uniffi_pman_lib_checksum_func_add_entity(
    ): Short
    fun uniffi_pman_lib_checksum_func_delete_entity(
    ): Short
    fun uniffi_pman_lib_checksum_func_search(
    ): Short
    fun uniffi_pman_lib_checksum_method_fileaction_get_file_name(
    ): Short
    fun uniffi_pman_lib_checksum_method_fileaction_get_data(
    ): Short
    fun uniffi_pman_lib_checksum_method_databasegroup_get_name(
    ): Short
    fun uniffi_pman_lib_checksum_method_databasegroup_get_id(
    ): Short
    fun uniffi_pman_lib_checksum_method_databasegroup_get_entities_count(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_name(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_group_id(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_user_id(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_password(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_url(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_property_names(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_get_property_value(
    ): Short
    fun uniffi_pman_lib_checksum_method_databaseentity_modify(
    ): Short
    fun ffi_pman_lib_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: _UniFFILib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 22
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_pman_lib_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: _UniFFILib) {
    if (lib.uniffi_pman_lib_checksum_func_lib_init() != 26793.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_create() != 62806.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_prepare() != 39598.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_is_read_only() != 10576.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_pre_open() != 59795.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_open() != 46739.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_save() != 49086.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_close() != 11056.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_set_argon2() != 29730.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_get_groups() != 56226.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_add_group() != 43636.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_delete_group() != 5206.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_get_users() != 58275.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_add_user() != 56469.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_delete_user() != 3477.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_get_entities() != 60582.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_add_entity() != 54179.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_delete_entity() != 10898.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_func_search() != 18297.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_fileaction_get_file_name() != 14148.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_fileaction_get_data() != 11569.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databasegroup_get_name() != 32122.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databasegroup_get_id() != 45252.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databasegroup_get_entities_count() != 60634.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_name() != 46136.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_group_id() != 42002.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_user_id() != 21757.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_password() != 16927.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_url() != 36390.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_property_names() != 20822.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_get_property_value() != 26480.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pman_lib_checksum_method_databaseentity_modify() != 57610.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Public interface members begin here.


public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteArr.size)
        rbuf.asByteBuffer()!!.put(byteArr)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        buf.putInt(byteArr.size)
        buf.put(byteArr)
    }
}

public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): Int {
        return 4 + value.size
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

// The base class for all UniFFI Object types.
//
// This class provides core operations for working with the Rust `Arc<T>` pointer to
// the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// the Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each `FFIObject` instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an `FFIObject` is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an `FFIObject` instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so will
//     leak the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each `FFIObject` an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// In the future we may be able to replace some of this with automatic finalization logic, such as using
// the new "Cleaner" functionaility in Java 9. The above scheme has been designed to work even if `destroy` is
// invoked by garbage-collection machinery rather than by calling code (which by the way, it's apparently also
// possible for the JVM to finalize an object while there is an in-flight call to one of its methods [1],
// so there would still be some complexity here).
//
// Sigh...all of this for want of a robust finalization mechanism.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//
abstract class FFIObject(
    protected val pointer: Pointer
): Disposable, AutoCloseable {

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    open protected fun freeRustArcPtr() {
        // To be overridden in subclasses.
    }

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.pointer)
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }
}

public interface DatabaseEntityInterface {
    @Throws(PmanException::class)
    fun `getName`(): String
    fun `getGroupId`(): UInt
    fun `getUserId`(): UInt@Throws(PmanException::class)
    fun `getPassword`(): String@Throws(PmanException::class)
    fun `getUrl`(): String?@Throws(PmanException::class)
    fun `getPropertyNames`(): Map<UInt, String>@Throws(PmanException::class)
    fun `getPropertyValue`(`id`: UInt): String@Throws(PmanException::class)
    fun `modify`(`newName`: String?, `newGroupId`: UInt?, `newUserId`: UInt?, `newPassword`: String?, `newUrl`: String?, `newProperties`: Map<String, String>, `modifiedProperties`: Map<UInt, String?>)
}

class DatabaseEntity(
    pointer: Pointer
) : FFIObject(pointer), DatabaseEntityInterface {

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.uniffi_pman_lib_fn_free_databaseentity(this.pointer, status)
        }
    }

    
    @Throws(PmanException::class)override fun `getName`(): String =
        callWithPointer {
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_name(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `getGroupId`(): UInt =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_group_id(it,
        
        _status)
}
        }.let {
            FfiConverterUInt.lift(it)
        }
    
    override fun `getUserId`(): UInt =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_user_id(it,
        
        _status)
}
        }.let {
            FfiConverterUInt.lift(it)
        }
    
    
    @Throws(PmanException::class)override fun `getPassword`(): String =
        callWithPointer {
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_password(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    
    @Throws(PmanException::class)override fun `getUrl`(): String? =
        callWithPointer {
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_url(it,
        
        _status)
}
        }.let {
            FfiConverterOptionalString.lift(it)
        }
    
    
    @Throws(PmanException::class)override fun `getPropertyNames`(): Map<UInt, String> =
        callWithPointer {
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_property_names(it,
        
        _status)
}
        }.let {
            FfiConverterMapUIntString.lift(it)
        }
    
    
    @Throws(PmanException::class)override fun `getPropertyValue`(`id`: UInt): String =
        callWithPointer {
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_get_property_value(it,
        FfiConverterUInt.lower(`id`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    
    @Throws(PmanException::class)override fun `modify`(`newName`: String?, `newGroupId`: UInt?, `newUserId`: UInt?, `newPassword`: String?, `newUrl`: String?, `newProperties`: Map<String, String>, `modifiedProperties`: Map<UInt, String?>) =
        callWithPointer {
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databaseentity_modify(it,
        FfiConverterOptionalString.lower(`newName`),FfiConverterOptionalUInt.lower(`newGroupId`),FfiConverterOptionalUInt.lower(`newUserId`),FfiConverterOptionalString.lower(`newPassword`),FfiConverterOptionalString.lower(`newUrl`),FfiConverterMapStringString.lower(`newProperties`),FfiConverterMapUIntOptionalString.lower(`modifiedProperties`),
        _status)
}
        }
    
    
    

    
}

public object FfiConverterTypeDatabaseEntity: FfiConverter<DatabaseEntity, Pointer> {
    override fun lower(value: DatabaseEntity): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): DatabaseEntity {
        return DatabaseEntity(value)
    }

    override fun read(buf: ByteBuffer): DatabaseEntity {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: DatabaseEntity) = 8

    override fun write(value: DatabaseEntity, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




public interface DatabaseGroupInterface {
    
    fun `getName`(): String
    fun `getId`(): UInt
    fun `getEntitiesCount`(): UInt
}

class DatabaseGroup(
    pointer: Pointer
) : FFIObject(pointer), DatabaseGroupInterface {

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.uniffi_pman_lib_fn_free_databasegroup(this.pointer, status)
        }
    }

    override fun `getName`(): String =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databasegroup_get_name(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `getId`(): UInt =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databasegroup_get_id(it,
        
        _status)
}
        }.let {
            FfiConverterUInt.lift(it)
        }
    
    override fun `getEntitiesCount`(): UInt =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_databasegroup_get_entities_count(it,
        
        _status)
}
        }.let {
            FfiConverterUInt.lift(it)
        }
    
    

    
}

public object FfiConverterTypeDatabaseGroup: FfiConverter<DatabaseGroup, Pointer> {
    override fun lower(value: DatabaseGroup): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): DatabaseGroup {
        return DatabaseGroup(value)
    }

    override fun read(buf: ByteBuffer): DatabaseGroup {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: DatabaseGroup) = 8

    override fun write(value: DatabaseGroup, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




public interface FileActionInterface {
    
    fun `getFileName`(): String
    fun `getData`(): ByteArray
}

class FileAction(
    pointer: Pointer
) : FFIObject(pointer), FileActionInterface {

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.uniffi_pman_lib_fn_free_fileaction(this.pointer, status)
        }
    }

    override fun `getFileName`(): String =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_fileaction_get_file_name(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `getData`(): ByteArray =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_method_fileaction_get_data(it,
        
        _status)
}
        }.let {
            FfiConverterByteArray.lift(it)
        }
    
    

    
}

public object FfiConverterTypeFileAction: FfiConverter<FileAction, Pointer> {
    override fun lower(value: FileAction): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): FileAction {
        return FileAction(value)
    }

    override fun read(buf: ByteBuffer): FileAction {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: FileAction) = 8

    override fun write(value: FileAction, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




enum class CryptoEngine {
    AES,CHACHA20;
}

public object FfiConverterTypeCryptoEngine: FfiConverterRustBuffer<CryptoEngine> {
    override fun read(buf: ByteBuffer) = try {
        CryptoEngine.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: CryptoEngine) = 4

    override fun write(value: CryptoEngine, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class HashAlgorithm {
    ARGON2;
}

public object FfiConverterTypeHashAlgorithm: FfiConverterRustBuffer<HashAlgorithm> {
    override fun read(buf: ByteBuffer) = try {
        HashAlgorithm.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: HashAlgorithm) = 4

    override fun write(value: HashAlgorithm, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class PasswordDatabaseType {
    KEE_PASS,PMAN;
}

public object FfiConverterTypePasswordDatabaseType: FfiConverterRustBuffer<PasswordDatabaseType> {
    override fun read(buf: ByteBuffer) = try {
        PasswordDatabaseType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PasswordDatabaseType) = 4

    override fun write(value: PasswordDatabaseType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class PmanException: Exception() {
    // Each variant is a nested class
    
    class ErrorMessage(
        val `errorText`: String
        ) : PmanException() {
        override val message
            get() = "errorText=${ `errorText` }"
    }
    

    companion object ErrorHandler : CallStatusErrorHandler<PmanException> {
        override fun lift(error_buf: RustBuffer.ByValue): PmanException = FfiConverterTypePmanError.lift(error_buf)
    }

    
}

public object FfiConverterTypePmanError : FfiConverterRustBuffer<PmanException> {
    override fun read(buf: ByteBuffer): PmanException {
        

        return when(buf.getInt()) {
            1 -> PmanException.ErrorMessage(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: PmanException): Int {
        return when(value) {
            is PmanException.ErrorMessage -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`errorText`)
            )
        }
    }

    override fun write(value: PmanException, buf: ByteBuffer) {
        when(value) {
            is PmanException.ErrorMessage -> {
                buf.putInt(1)
                FfiConverterString.write(value.`errorText`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




public object FfiConverterOptionalUInt: FfiConverterRustBuffer<UInt?> {
    override fun read(buf: ByteBuffer): UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: UInt?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




public object FfiConverterOptionalByteArray: FfiConverterRustBuffer<ByteArray?> {
    override fun read(buf: ByteBuffer): ByteArray? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterByteArray.read(buf)
    }

    override fun allocationSize(value: ByteArray?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterByteArray.allocationSize(value)
        }
    }

    override fun write(value: ByteArray?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterByteArray.write(value, buf)
        }
    }
}




public object FfiConverterSequenceString: FfiConverterRustBuffer<List<String>> {
    override fun read(buf: ByteBuffer): List<String> {
        val len = buf.getInt()
        return List<String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<String>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




public object FfiConverterSequenceByteArray: FfiConverterRustBuffer<List<ByteArray>> {
    override fun read(buf: ByteBuffer): List<ByteArray> {
        val len = buf.getInt()
        return List<ByteArray>(len) {
            FfiConverterByteArray.read(buf)
        }
    }

    override fun allocationSize(value: List<ByteArray>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterByteArray.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ByteArray>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterByteArray.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeDatabaseGroup: FfiConverterRustBuffer<List<DatabaseGroup>> {
    override fun read(buf: ByteBuffer): List<DatabaseGroup> {
        val len = buf.getInt()
        return List<DatabaseGroup>(len) {
            FfiConverterTypeDatabaseGroup.read(buf)
        }
    }

    override fun allocationSize(value: List<DatabaseGroup>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeDatabaseGroup.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<DatabaseGroup>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeDatabaseGroup.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeFileAction: FfiConverterRustBuffer<List<FileAction>> {
    override fun read(buf: ByteBuffer): List<FileAction> {
        val len = buf.getInt()
        return List<FileAction>(len) {
            FfiConverterTypeFileAction.read(buf)
        }
    }

    override fun allocationSize(value: List<FileAction>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeFileAction.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FileAction>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeFileAction.write(it, buf)
        }
    }
}



public object FfiConverterMapUIntString: FfiConverterRustBuffer<Map<UInt, String>> {
    override fun read(buf: ByteBuffer): Map<UInt, String> {
        // TODO: Once Kotlin's `buildMap` API is stabilized we should use it here.
        val items : MutableMap<UInt, String> = mutableMapOf()
        val len = buf.getInt()
        repeat(len) {
            val k = FfiConverterUInt.read(buf)
            val v = FfiConverterString.read(buf)
            items[k] = v
        }
        return items
    }

    override fun allocationSize(value: Map<UInt, String>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterUInt.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<UInt, String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterUInt.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}



public object FfiConverterMapUIntTypeDatabaseEntity: FfiConverterRustBuffer<Map<UInt, DatabaseEntity>> {
    override fun read(buf: ByteBuffer): Map<UInt, DatabaseEntity> {
        // TODO: Once Kotlin's `buildMap` API is stabilized we should use it here.
        val items : MutableMap<UInt, DatabaseEntity> = mutableMapOf()
        val len = buf.getInt()
        repeat(len) {
            val k = FfiConverterUInt.read(buf)
            val v = FfiConverterTypeDatabaseEntity.read(buf)
            items[k] = v
        }
        return items
    }

    override fun allocationSize(value: Map<UInt, DatabaseEntity>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterUInt.allocationSize(k) +
            FfiConverterTypeDatabaseEntity.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<UInt, DatabaseEntity>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterUInt.write(k, buf)
            FfiConverterTypeDatabaseEntity.write(v, buf)
        }
    }
}



public object FfiConverterMapUIntOptionalString: FfiConverterRustBuffer<Map<UInt, String?>> {
    override fun read(buf: ByteBuffer): Map<UInt, String?> {
        // TODO: Once Kotlin's `buildMap` API is stabilized we should use it here.
        val items : MutableMap<UInt, String?> = mutableMapOf()
        val len = buf.getInt()
        repeat(len) {
            val k = FfiConverterUInt.read(buf)
            val v = FfiConverterOptionalString.read(buf)
            items[k] = v
        }
        return items
    }

    override fun allocationSize(value: Map<UInt, String?>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterUInt.allocationSize(k) +
            FfiConverterOptionalString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<UInt, String?>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterUInt.write(k, buf)
            FfiConverterOptionalString.write(v, buf)
        }
    }
}



public object FfiConverterMapUIntMapUIntTypeDatabaseEntity: FfiConverterRustBuffer<Map<UInt, Map<UInt, DatabaseEntity>>> {
    override fun read(buf: ByteBuffer): Map<UInt, Map<UInt, DatabaseEntity>> {
        // TODO: Once Kotlin's `buildMap` API is stabilized we should use it here.
        val items : MutableMap<UInt, Map<UInt, DatabaseEntity>> = mutableMapOf()
        val len = buf.getInt()
        repeat(len) {
            val k = FfiConverterUInt.read(buf)
            val v = FfiConverterMapUIntTypeDatabaseEntity.read(buf)
            items[k] = v
        }
        return items
    }

    override fun allocationSize(value: Map<UInt, Map<UInt, DatabaseEntity>>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterUInt.allocationSize(k) +
            FfiConverterMapUIntTypeDatabaseEntity.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<UInt, Map<UInt, DatabaseEntity>>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterUInt.write(k, buf)
            FfiConverterMapUIntTypeDatabaseEntity.write(v, buf)
        }
    }
}



public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<String, String>> {
    override fun read(buf: ByteBuffer): Map<String, String> {
        // TODO: Once Kotlin's `buildMap` API is stabilized we should use it here.
        val items : MutableMap<String, String> = mutableMapOf()
        val len = buf.getInt()
        repeat(len) {
            val k = FfiConverterString.read(buf)
            val v = FfiConverterString.read(buf)
            items[k] = v
        }
        return items
    }

    override fun allocationSize(value: Map<String, String>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<String, String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}

fun `libInit`() =
    
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_lib_init(_status)
}


@Throws(PmanException::class)

fun `create`(`databaseType`: PasswordDatabaseType, `passwordHash`: ByteArray, `password2Hash`: ByteArray?, `keyFileContents`: ByteArray?): ULong {
    return FfiConverterULong.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_create(FfiConverterTypePasswordDatabaseType.lower(`databaseType`),FfiConverterByteArray.lower(`passwordHash`),FfiConverterOptionalByteArray.lower(`password2Hash`),FfiConverterOptionalByteArray.lower(`keyFileContents`),_status)
})
}

@Throws(PmanException::class)

fun `prepare`(`data`: ByteArray, `fileName`: String): ULong {
    return FfiConverterULong.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_prepare(FfiConverterByteArray.lower(`data`),FfiConverterString.lower(`fileName`),_status)
})
}

@Throws(PmanException::class)

fun `isReadOnly`(`databaseId`: ULong): Boolean {
    return FfiConverterBoolean.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_is_read_only(FfiConverterULong.lower(`databaseId`),_status)
})
}

@Throws(PmanException::class)

fun `preOpen`(`databaseId`: ULong, `passwordHash`: ByteArray, `password2Hash`: ByteArray?, `keyFileContents`: ByteArray?): List<String> {
    return FfiConverterSequenceString.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_pre_open(FfiConverterULong.lower(`databaseId`),FfiConverterByteArray.lower(`passwordHash`),FfiConverterOptionalByteArray.lower(`password2Hash`),FfiConverterOptionalByteArray.lower(`keyFileContents`),_status)
})
}

@Throws(PmanException::class)

fun `open`(`databaseId`: ULong, `data`: List<ByteArray>) =
    
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_open(FfiConverterULong.lower(`databaseId`),FfiConverterSequenceByteArray.lower(`data`),_status)
}


@Throws(PmanException::class)

fun `save`(`databaseId`: ULong): List<FileAction> {
    return FfiConverterSequenceTypeFileAction.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_save(FfiConverterULong.lower(`databaseId`),_status)
})
}

@Throws(PmanException::class)

fun `close`(`databaseId`: ULong) =
    
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_close(FfiConverterULong.lower(`databaseId`),_status)
}


@Throws(PmanException::class)

fun `setArgon2`(`databaseId`: ULong, `hashId`: ULong, `iterations`: ULong, `parallelism`: ULong, `memory`: ULong) =
    
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_set_argon2(FfiConverterULong.lower(`databaseId`),FfiConverterULong.lower(`hashId`),FfiConverterULong.lower(`iterations`),FfiConverterULong.lower(`parallelism`),FfiConverterULong.lower(`memory`),_status)
}


@Throws(PmanException::class)

fun `getGroups`(`databaseId`: ULong): List<DatabaseGroup> {
    return FfiConverterSequenceTypeDatabaseGroup.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_get_groups(FfiConverterULong.lower(`databaseId`),_status)
})
}

@Throws(PmanException::class)

fun `addGroup`(`databaseId`: ULong, `name`: String): UInt {
    return FfiConverterUInt.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_add_group(FfiConverterULong.lower(`databaseId`),FfiConverterString.lower(`name`),_status)
})
}

@Throws(PmanException::class)

fun `deleteGroup`(`databaseId`: ULong, `id`: UInt) =
    
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_delete_group(FfiConverterULong.lower(`databaseId`),FfiConverterUInt.lower(`id`),_status)
}


@Throws(PmanException::class)

fun `getUsers`(`databaseId`: ULong): Map<UInt, String> {
    return FfiConverterMapUIntString.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_get_users(FfiConverterULong.lower(`databaseId`),_status)
})
}

@Throws(PmanException::class)

fun `addUser`(`databaseId`: ULong, `name`: String): UInt {
    return FfiConverterUInt.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_add_user(FfiConverterULong.lower(`databaseId`),FfiConverterString.lower(`name`),_status)
})
}

@Throws(PmanException::class)

fun `deleteUser`(`databaseId`: ULong, `id`: UInt) =
    
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_delete_user(FfiConverterULong.lower(`databaseId`),FfiConverterUInt.lower(`id`),_status)
}


@Throws(PmanException::class)

fun `getEntities`(`databaseId`: ULong, `groupId`: UInt): Map<UInt, DatabaseEntity> {
    return FfiConverterMapUIntTypeDatabaseEntity.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_get_entities(FfiConverterULong.lower(`databaseId`),FfiConverterUInt.lower(`groupId`),_status)
})
}

@Throws(PmanException::class)

fun `addEntity`(`databaseId`: ULong, `name`: String, `groupId`: UInt, `userId`: UInt, `password`: String, `url`: String?, `properties`: Map<String, String>): UInt {
    return FfiConverterUInt.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_add_entity(FfiConverterULong.lower(`databaseId`),FfiConverterString.lower(`name`),FfiConverterUInt.lower(`groupId`),FfiConverterUInt.lower(`userId`),FfiConverterString.lower(`password`),FfiConverterOptionalString.lower(`url`),FfiConverterMapStringString.lower(`properties`),_status)
})
}

@Throws(PmanException::class)

fun `deleteEntity`(`databaseId`: ULong, `id`: UInt) =
    
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_delete_entity(FfiConverterULong.lower(`databaseId`),FfiConverterUInt.lower(`id`),_status)
}


@Throws(PmanException::class)

fun `search`(`databaseId`: ULong, `searchString`: String): Map<UInt, Map<UInt, DatabaseEntity>> {
    return FfiConverterMapUIntMapUIntTypeDatabaseEntity.lift(
    rustCallWithError(PmanException) { _status ->
    _UniFFILib.INSTANCE.uniffi_pman_lib_fn_func_search(FfiConverterULong.lower(`databaseId`),FfiConverterString.lower(`searchString`),_status)
})
}


