[package]
name = "pman_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
uniffi = { version = "0.24.3", features = [ "cli" ] }
thiserror = "1.0"
rand = "0.8.5"

[build-dependencies]
uniffi_build = "0.24.3"
uniffi_bindgen = "0.24.3"