pub const DATABASE_VERSION_ID: u32 = 1;
pub const HASH_ALGORITHM_PROPERTIES_ID: u32 = 2;
pub const ENCRYPTION_ALGORITHM_PROPERTIES_ID: u32 = 3;
pub const NAMES_FILES_LOCATIONS_ID: u32 = 4;
pub const PASSWORDS_FILES_LOCATIONS_ID: u32 = 5;
