pub const DATABASE_VERSION_ID: u32 = 1;
pub const HASH_ALGORITHM_PROPERTIES_ID: u32 = 2;
pub const ENCRYPTION_ALGORITHM1_PROPERTIES_ID: u32 = 3;
pub const ENCRYPTION_ALGORITHM2_PROPERTIES_ID: u32 = 4;
pub const FILE_LOCATION_ID: u32 = 5;

pub const HISTORY_LENGTH_ID: u32 = 6;